#!/usr/bin/env node
/**
 * Builds the static, serverless bundle deployed to Cloudflare Pages.
 *
 * Cloudflare Workers cannot run this project's backend: better-sqlite3 is a
 * native addon, Express needs a Node http server, and server/index.js reads
 * verticals off disk at boot. None of that has an edge equivalent, so the
 * static build drops the backend entirely rather than pretending to port it.
 *
 * What survives is the calculator itself, which turns out to need no server at
 * all — shared/engine.js is already UMD and prices a job entirely in the
 * browser. What does NOT survive is everything the backend was for: tenants,
 * lead capture, the dashboard, auth, and CRM webhooks.
 *
 * Nothing in the source tree is modified; every transform is applied on the way
 * into dist/, so `npm start` keeps working against the real server.
 */
const fs = require('fs');
const path = require('path');

const ROOT = __dirname;
const DIST = path.join(ROOT, 'dist');

/** The tenant baked into the static build, standing in for a DB row. */
const DEMO_SLUG = 'demo';
const DEFAULT_VERTICAL = 'residential-cleaning';

/** Mirrors DEFAULT_BRANDING in server/index.js. Keep the two in sync. */
const DEFAULT_BRANDING = {
  accent: '#5C4F87',
  headline: 'Get your instant price',
  subhead: 'Answer a few questions and see your price right now — no waiting on a callback.',
  ctaLabel: 'Email me this quote',
  showRecurring: true,
  showRange: true,
  showDuration: true,
  thanksMessage: "Thanks! We've got your details and will be in touch shortly to confirm your booking.",
  showLanguageToggle: true,
  headlineEs: 'Obtén tu precio al instante',
  subheadEs: 'Responde unas preguntas y mira tu precio ahora mismo — sin esperar una llamada.',
  ctaLabelEs: 'Envíame este presupuesto',
  thanksMessageEs: 'Gracias, ya tenemos tus datos. Te contactamos en breve para confirmar.'
};

const read = p => fs.readFileSync(path.join(ROOT, p), 'utf8');
const write = (rel, body) => {
  const dest = path.join(DIST, rel);
  fs.mkdirSync(path.dirname(dest), { recursive: true });
  fs.writeFileSync(dest, body);
  return dest;
};
const copy = (rel, destRel = rel) => {
  const dest = path.join(DIST, destRel);
  fs.mkdirSync(path.dirname(dest), { recursive: true });
  fs.copyFileSync(path.join(ROOT, rel), dest);
};

fs.rmSync(DIST, { recursive: true, force: true });
fs.mkdirSync(DIST, { recursive: true });

/* ── 1. verticals → a single JS object, since there is no fs at runtime ──── */
const verticals = {};
fs.readdirSync(path.join(ROOT, 'verticals'))
  .filter(f => f.endsWith('.json'))
  .forEach(f => {
    const v = JSON.parse(read(path.join('verticals', f)));
    verticals[v.vertical || path.basename(f, '.json')] = v;
  });

if (!verticals[DEFAULT_VERTICAL]) {
  throw new Error(`Missing default vertical "${DEFAULT_VERTICAL}" in verticals/`);
}

/**
 * Replaces GET /api/public/config/:slug. The widget reads this instead of
 * fetching, so the calculator boots with no network round-trip at all.
 */
write('config.js', `/* Generated by build-static.js — do not edit. */
window.QUOTECRAFT_STATIC = ${JSON.stringify({
  slug: DEMO_SLUG,
  businessName: 'QuoteCraft Demo',
  vertical: DEFAULT_VERTICAL,
  verticals,
  branding: DEFAULT_BRANDING
}, null, 2)};
`);

/* ── 2. widget.js — swap the two API calls for static behaviour ─────────── */
let widgetJs = read('widget/widget.js');

// SLUG came from the /w/:slug path, which no longer exists. embed.js passes it
// as ?slug= instead, and it must round-trip exactly: embed.js drops any
// postMessage whose slug doesn't match its data-quotecraft attribute, so
// getting this wrong silently breaks iframe auto-height.
widgetJs = widgetJs.replace(
  "var SLUG = location.pathname.split('/').filter(Boolean).pop();",
  "var SLUG = new URLSearchParams(location.search).get('slug') ||\n    (window.QUOTECRAFT_STATIC && window.QUOTECRAFT_STATIC.slug) || 'demo';"
);

// Boot from the baked config instead of GET /api/public/config/:slug.
const bootNeedle = "fetch('/api/public/config/' + encodeURIComponent(SLUG))\n    .then(function (r) { if (!r.ok) throw new Error('not found'); return r.json(); })\n    .then(";
if (!widgetJs.includes(bootNeedle)) throw new Error('widget.js boot fetch not found — build needs updating');
widgetJs = widgetJs.replace(
  bootNeedle,
  `Promise.resolve((function () {
    var S = window.QUOTECRAFT_STATIC;
    var q = new URLSearchParams(location.search).get('vertical');
    var key = (q && S.verticals[q]) ? q : S.vertical;
    return { config: S.verticals[key], branding: S.branding, businessName: S.businessName };
  })())
    .then(`
);

// There is no lead endpoint and no database. Rather than silently swallow the
// submission, hand the quote to the visitor and tell them plainly.
const leadNeedle = "    fetch('/api/public/lead/' + encodeURIComponent(SLUG), {";
if (!widgetJs.includes(leadNeedle)) throw new Error('widget.js lead fetch not found — build needs updating');
const leadStart = widgetJs.indexOf(leadNeedle);
const leadEnd = widgetJs.indexOf('\n  }\n', leadStart);
if (leadEnd === -1) throw new Error('could not delimit sendLead() — build needs updating');

widgetJs = widgetJs.slice(0, leadStart) + `    // Static build: no backend, so nothing is transmitted or stored. The
    // quote is handed back to the visitor to send on themselves.
    var payload = {
      name: document.getElementById('lName').value.trim(),
      email: email, phone: phone,
      address: document.getElementById('lAddress').value.trim(),
      note: document.getElementById('lNote').value.trim(),
      input: input, lang: lang
    };
    try { sessionStorage.setItem('quotecraft:lastQuote', JSON.stringify(payload)); } catch (_) {}

    branding.thanksMessage = 'This is a demo calculator, so your details were not sent anywhere. ' +
      'Copy your quote above and email it to us to book.';
    branding.thanksMessageEs = 'Esta es una calculadora de demostración: tus datos no se enviaron a ningún sitio. ' +
      'Copia tu presupuesto y envíanoslo por correo para reservar.';
    stage = 'thanks';
    render();
    try { parent.postMessage({ type: 'quotecraft:lead', slug: SLUG, static: true }, '*'); } catch (_) {}
` + widgetJs.slice(leadEnd);

write('widget/widget.js', widgetJs);

/* ── 3. widget.html — load the baked config before the widget ───────────── */
let widgetHtml = read('widget/widget.html');
widgetHtml = widgetHtml.replace(
  '<script src="/shared/engine.js"></script>',
  '<script src="/config.js"></script>\n<script src="/shared/engine.js"></script>'
);
write('widget/index.html', widgetHtml);
// /w/<anything> used to be a server route; keep one working URL for embeds.
write('w/index.html', widgetHtml);

/* ── 4. embed.js — point the iframe at the static widget path ───────────── */
let embedJs = read('widget/embed.js');
embedJs = embedJs.replace(
  "frame.src = origin + '/w/' + encodeURIComponent(slug);",
  "frame.src = origin + '/widget/?slug=' + encodeURIComponent(slug);"
);
write('embed.js', embedJs);

/* ── 5. static pages that never needed the API ──────────────────────────── */
copy('shared/engine.js');
copy('public/assets/theme.css', 'assets/theme.css');
copy('public/assets/favicon.svg', 'assets/favicon.svg');
copy('public/404.html', '404.html');
copy('public/index.html', 'index.html');

// demo.html embeds via /embed.js, which now resolves to the static widget.
copy('public/demo.html', 'demo/index.html');

// The standalone single-file calculator — self-contained, no API, no config.
copy('index.html', 'calculator/index.html');

/* ── 6. drop the pages whose whole purpose was the backend ──────────────── */
// public/login.html      → POSTs /api/auth/login
// public/signup.html     → POSTs /api/auth/signup
// public/app/dashboard.* → 9 authenticated /api/* endpoints
// Serving dead forms is worse than serving nothing; /_redirects sends them to
// a page that explains the situation.
write('unavailable/index.html', `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8"/>
<meta name="viewport" content="width=device-width, initial-scale=1.0"/>
<title>Not part of this demo · QuoteCraft</title>
<link rel="icon" href="/assets/favicon.svg" type="image/svg+xml"/>
<link rel="stylesheet" href="/assets/theme.css"/>
<style>
  .wrap { max-width: 560px; margin: 0 auto; padding: 90px 24px; text-align: center; }
  .wrap h1 { margin-bottom: 14px; }
  .wrap p { color: var(--ink-600); font-size: 15px; line-height: 1.65; margin-bottom: 12px; }
  .wrap .actions { margin-top: 28px; display: flex; gap: 12px; justify-content: center; flex-wrap: wrap; }
</style>
</head>
<body>
<div class="wrap">
  <h1>That part needs the server</h1>
  <p>Accounts, saved leads and the dashboard run on the QuoteCraft backend,
     which isn't part of this static deployment.</p>
  <p>The calculator itself works in full — it prices everything in your browser.</p>
  <div class="actions">
    <a class="btn btn-primary" href="/demo/">Try the calculator</a>
    <a class="btn" href="/">Back to home</a>
  </div>
</div>
</body>
</html>
`);

/* ── 7. Pages routing + headers ─────────────────────────────────────────── */
write('_redirects', `# Backend-only routes — see unavailable/index.html
/login      /unavailable/  302
/signup     /unavailable/  302
/app        /unavailable/  302
/app/*      /unavailable/  302
/api/*      /unavailable/  302

# Former Express routes kept working as static paths
/demo       /demo/         301
/w/*        /widget/       301
`);

write('_headers', `/embed.js
  Access-Control-Allow-Origin: *
  Cache-Control: public, max-age=300

/widget/*
  Access-Control-Allow-Origin: *

/shared/engine.js
  Cache-Control: public, max-age=3600

/assets/*
  Cache-Control: public, max-age=3600
`);

/* ── report ─────────────────────────────────────────────────────────────── */
let files = 0, bytes = 0;
(function walk(dir) {
  for (const e of fs.readdirSync(dir, { withFileTypes: true })) {
    const p = path.join(dir, e.name);
    if (e.isDirectory()) walk(p);
    else { files++; bytes += fs.statSync(p).size; }
  }
})(DIST);

console.log(`dist/ built — ${files} files, ${(bytes / 1024).toFixed(0)} KB`);
console.log('Cloudflare Pages limits: 20,000 files, 25 MiB per file.');
